### PR TITLE
Added hamburger menu for navbar

### PR DESCRIPTION
**Pull request by Sekiraw**
I don't trust my creativity about the icons

### CODE REVIEW

**Comment by Sekiraw** [comment]
References #1

**Comment by novialriptide** [comment]
Hi, thanks for contributing to https://pyga.me/.

Could you use this icon library as mentioned in the issue? https://fonts.google.com/icons
I would like to minimize the number of dependencies we use.

**Comment by Sekiraw** [comment]
I'm not sure about the colors, but I wasn't able to change the color of the icon, so I've made a bar for that, otherwise it would be invisible as it's almost the same color as the background.

**Comment by novialriptide** [comment]
Thanks for wanting to contribute to https://pyga.me. I took a deeper look into the pull request and realized that this was difficult for beginners to pull off and never should've had the "good-first-issue" tag. I hope you've learned something about React, HTML, or CSS from this pull request.

I'm going to close this pull request based on the reasons above. I hope the work you put in would get you acquainted with the existing codebase. Thanks again.

**Pull request closed without merging**
